//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suota_pgp.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("suota_pgp.Data.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth must be on..
        /// </summary>
        internal static string BluetoothIsNotOn {
            get {
                return ResourceManager.GetString("BluetoothIsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to a device in the middle of a scan..
        /// </summary>
        internal static string CannotConnectInScan {
            get {
                return ResourceManager.GetString("CannotConnectInScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t setup notify on a Characteristic in the middle of a scan..
        /// </summary>
        internal static string CannotNotifyCharacteristicInScan {
            get {
                return ResourceManager.GetString("CannotNotifyCharacteristicInScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read a Characteristic in the middle of a scan..
        /// </summary>
        internal static string CannotReadCharacteristicInScan {
            get {
                return ResourceManager.GetString("CannotReadCharacteristicInScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove notify on a Characteristic in the middle of a scan..
        /// </summary>
        internal static string CannotUnnotifyCharacteristicInScan {
            get {
                return ResourceManager.GetString("CannotUnnotifyCharacteristicInScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to a Characteristic in the middle of a scan..
        /// </summary>
        internal static string CannotWriteCharacteristicInScan {
            get {
                return ResourceManager.GetString("CannotWriteCharacteristicInScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic is not readable..
        /// </summary>
        internal static string CharacteristicNotReadable {
            get {
                return ResourceManager.GetString("CharacteristicNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic is not writable..
        /// </summary>
        internal static string CharacteristicNotWritable {
            get {
                return ResourceManager.GetString("CharacteristicNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device already connected..
        /// </summary>
        internal static string DeviceAlreadyConnected {
            get {
                return ResourceManager.GetString("DeviceAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not connected..
        /// </summary>
        internal static string DeviceNotConnected {
            get {
                return ResourceManager.GetString("DeviceNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device must be patched..
        /// </summary>
        internal static string DeviceNotPatched {
            get {
                return ResourceManager.GetString("DeviceNotPatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write Characteristic..
        /// </summary>
        internal static string FailedToWriteCharacteristic {
            get {
                return ResourceManager.GetString("FailedToWriteCharacteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be less than {0}.
        /// </summary>
        internal static string LengthMustBeLessThanChunkSize {
            get {
                return ResourceManager.GetString("LengthMustBeLessThanChunkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect. Failed after {0} attempts..
        /// </summary>
        internal static string UnableToConnect {
            get {
                return ResourceManager.GetString("UnableToConnect", resourceCulture);
            }
        }
    }
}
