//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suota_pgp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("suota_pgp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob Key:.
        /// </summary>
        internal static string BlobKeyString {
            get {
                return ResourceManager.GetString("BlobKeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Address:.
        /// </summary>
        internal static string BluetoothAddressString {
            get {
                return ResourceManager.GetString("BluetoothAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Bluetooth adapter is disabled.
        /// </summary>
        internal static string BluetoothDisabledString {
            get {
                return ResourceManager.GetString("BluetoothDisabledString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be a(n) {0}..
        /// </summary>
        internal static string ConverterValueError {
            get {
                return ResourceManager.GetString("ConverterValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Key:.
        /// </summary>
        internal static string DeviceKeyString {
            get {
                return ResourceManager.GetString("DeviceKeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Please enable location and storage permissions.
        /// </summary>
        internal static string EnableLocationAndStorageString {
            get {
                return ResourceManager.GetString("EnableLocationAndStorageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Please enable location permissions.
        /// </summary>
        internal static string EnableLocationString {
            get {
                return ResourceManager.GetString("EnableLocationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Please enable storage permissions.
        /// </summary>
        internal static string EnableStorageString {
            get {
                return ResourceManager.GetString("EnableStorageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware File.
        /// </summary>
        internal static string FirmwareFileString {
            get {
                return ResourceManager.GetString("FirmwareFileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Device Info.
        /// </summary>
        internal static string GetDeviceInfoString {
            get {
                return ResourceManager.GetString("GetDeviceInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Extractor.
        /// </summary>
        internal static string KeyExtractorString {
            get {
                return ResourceManager.GetString("KeyExtractorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired Pokemon GO Plus.
        /// </summary>
        internal static string PairedPokemonGoPlusString {
            get {
                return ResourceManager.GetString("PairedPokemonGoPlusString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Device.
        /// </summary>
        internal static string PatchDeviceString {
            get {
                return ResourceManager.GetString("PatchDeviceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patched Pokemon GO Plus.
        /// </summary>
        internal static string PatchedPokemonGoPlusString {
            get {
                return ResourceManager.GetString("PatchedPokemonGoPlusString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon GO Plus.
        /// </summary>
        internal static string PokemonGoPlusString {
            get {
                return ResourceManager.GetString("PokemonGoPlusString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string RefreshString {
            get {
                return ResourceManager.GetString("RefreshString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore PGP.
        /// </summary>
        internal static string RestorePgpString {
            get {
                return ResourceManager.GetString("RestorePgpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveString {
            get {
                return ResourceManager.GetString("SaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string ScanString {
            get {
                return ResourceManager.GetString("ScanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Patch.
        /// </summary>
        internal static string StartPatchString {
            get {
                return ResourceManager.GetString("StartPatchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Scanning.
        /// </summary>
        internal static string StopScanString {
            get {
                return ResourceManager.GetString("StopScanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessString {
            get {
                return ResourceManager.GetString("SuccessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your Pokemon GO Plus near your phone until the update process is complete..
        /// </summary>
        internal static string SuotaInProgressDescString {
            get {
                return ResourceManager.GetString("SuotaInProgressDescString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUOTA in progress.
        /// </summary>
        internal static string SuotaInProgressString {
            get {
                return ResourceManager.GetString("SuotaInProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon GO Plus Key Extractor.
        /// </summary>
        internal static string TitleString {
            get {
                return ResourceManager.GetString("TitleString", resourceCulture);
            }
        }
    }
}
